language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --no-interaction --prefer-dist
  - php vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard
script:
  - vendor/bin/composer coding-standard
