<?php
/**
 * Frenet Shipping Gateway
 *
 * @category Frenet
 * @package Frenet\Shipping
 *
 * @author Tiago Sampaio <tiago@tiagosampaio.com>
 * @link https://github.com/tiagosampaio
 * @link https://tiagosampaio.com
 *
 * Copyright (c) 2020.
 */

/** @var $block \Frenet\Shipping\Block\Catalog\Product\View\Quote */

$product = $block->getProduct();
?>
<?php if ($product->isSaleable()) :?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "frenet-quote": {
                        "component": "Frenet_Shipping/js/catalog/product/view/quote",
                        "api_url": "<?= $block->escapeJs($block->getApiUrl()) ?>",
                        "blockTitle": "<?= $block->escapeJs(__('Shipping Quote')) ?>",
                        "blockDescription": "<?= $block->escapeJs(__('Calculate the shipping quote for this product with Frenet.')) ?>",
                        "fieldTitle": "<?= $block->escapeJs(__('Postcode')) ?>",
                        "buttonTitle": "<?= $block->escapeJs(__('Get Quote')) ?>",
                        "noResultsMessage": "<?= $block->escapeJs(__('Sorry. No quotes were found for this postcode.')) ?>"
                    }
                }
            }
        }
    }
    </script>
    <div class="box-frenet-quote" data-bind="scope: 'frenet-quote'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
<?php endif; ?>
